name: test
on:
  - push
  - pull_request
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        node-version:
          - 14.17.0
          - 16.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Run tests
        run: npm test
        env:
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_PRIVATE_BUCKET: adonis-drive-r2-private
          R2_PUBLIC_BUCKET: adonis-drive-r2-public
          R2_PUBLIC_BUCKET_PUBLIC_URL: ${{ secrets.R2_PUBLIC_BUCKET_PUBLIC_URL }}
          R2_PRIVATE_BUCKET_PUBLIC_URL: ${{ secrets.R2_PRIVATE_BUCKET_PUBLIC_URL }}
  windows:
    runs-on: windows-latest
    needs: linux
    strategy:
      max-parallel: 1
      matrix:
        node-version:
          - 14.17.0
          - 16.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Run tests
        run: npm test
        env:
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_PRIVATE_BUCKET: adonis-drive-r2-private
          R2_PUBLIC_BUCKET: adonis-drive-r2-public
          R2_PUBLIC_BUCKET_PUBLIC_URL: ${{ secrets.R2_PUBLIC_BUCKET_PUBLIC_URL }}
          R2_PRIVATE_BUCKET_PUBLIC_URL: ${{ secrets.R2_PRIVATE_BUCKET_PUBLIC_URL }}
